### ISSUE TITLE
Question: CommandHandler function

### ISSUE THREAD

**Issue by MassiCav** [Ocramius/event-sourcing-workshop#49]
Hello Marco,
in the 'Commanding' documentation the following statement:
```
A CommandHandler is a function that:
exposes the Command type that it supports
delegates execution of actual work to the business domain, by talking to other infrastructural components (repositories, external services) in the process.
```
I fail to grasp the use cases for having CommandHandlers interacting with other components.
Could you elaborate on that and maybe give a real (simple) example?

TIA and BR,
M.

**Comment by Ocramius** [comment]
Here's an example:

https://github.com/Ocramius/event-sourcing-workshop/blob/1ad0cbcbc5afea60bedf63f8a066a015f1530877/src/Payment/Infrastructure/CommandHandler/HandleSendNotificationsForLatePayments.php#L29-L52

This command handler talks to the DB (infrastructural component) and some notification system (in this case `printOutput`, for the sake of the workshop).

Obviously, the example is a bit rough, but here's where you'd see a "payment gateway", a mailer, etc.
